export const ActionTypes = {
    SET_PRODUCTS : "SET_PRODUCTS",
    CREATE_CALORIE_INFO:"CREATE_CALORIE_INFO",
    CALORIE_INFO_LIST: "CALORIE_INFO_LIST",
    CATEGORY_LIST:"CATEGORY_LIST",
    USER_REGISTER:"USER_REGISTER",
    USER_SIGNIN:"USER_SIGNIN", // Düzeltildi
    USER_INFO: "USER_INFO"
  }
  